AdaptiveMultiChebySpectral: SP1D_AdaptiveMultiChebySpectral.cpp headers_Cheby/input.h headers_Cheby/write.h
	g++ SP1D_AdaptiveMultiChebySpectral.cpp -o SP1D_AdaptiveMultiChebySpectral --std=c++17 -O3

SingleP: SP1D_AdaptiveMultiChebySpectral_SingleP.cpp headers_Cheby/input.h headers_Cheby/write.h
	g++ SP1D_AdaptiveMultiChebySpectral_SingleP.cpp -o SingleP --std=c++17 -O3

AdaptiveMultiChebySpectral_exp: SP1D_AdaptiveMultiChebySpectral_exp.cpp headers_Cheby/input.h headers_Cheby/write.h
	g++ SP1D_AdaptiveMultiChebySpectral_exp.cpp -o SP1D_AdaptiveMultiChebySpectral_exp --std=c++17 -O3

GAMER: SP1D_AdaptiveMultiChebySpectral_exp_GAMER.cpp headers_Cheby/input.h headers_Cheby/write.h
	g++ SP1D_AdaptiveMultiChebySpectral_exp_GAMER.cpp -o SP1D_AdaptiveMultiChebySpectral_exp --std=c++17 -O3
